"""
Export Service — LaTeX and Word output for generated research papers.

LaTeX: Assembles sections + citations into a .tex file, optionally compiles
       via the existing paper_editor compile pipeline.
Word:  Generates a .docx with academic formatting via python-docx.
"""

from __future__ import annotations

import logging
import tempfile
from pathlib import Path
from typing import Optional

from modules.code_mapper.models.code_mapper_models import (
    CitationEntry,
    PaperSectionDraft,
    RepoStructure,
)

logger = logging.getLogger(__name__)

_WORK_DIR = Path(tempfile.gettempdir()) / "code_mapper_exports"
_WORK_DIR.mkdir(parents=True, exist_ok=True)

_TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates" / "latex"


# ---------------------------------------------------------------------------
# LaTeX export
# ---------------------------------------------------------------------------

def export_latex(
    repo: RepoStructure,
    sections: list[PaperSectionDraft],
    citations: list[CitationEntry],
    bibtex: str,
    job_id: str,
    style: str = "generic",
) -> Path:
    """Generate a complete .tex + .bib file set.

    Returns the path to the output directory containing main.tex and refs.bib.
    """

    out_dir = _WORK_DIR / job_id / "latex"
    out_dir.mkdir(parents=True, exist_ok=True)

    tex_content = _render_latex(repo, sections, style)
    (out_dir / "main.tex").write_text(tex_content, encoding="utf-8")

    if bibtex:
        (out_dir / "refs.bib").write_text(bibtex, encoding="utf-8")

    logger.info("LaTeX exported to %s", out_dir)
    return out_dir


def _render_latex(
    repo: RepoStructure,
    sections: list[PaperSectionDraft],
    style: str,
) -> str:
    preamble = _get_preamble(style)
    title = repo.name.replace("_", " ").title()

    body_parts: list[str] = []
    for sec in sections:
        if sec.section_id == "abstract":
            body_parts.append(f"\\begin{{abstract}}\n{sec.content}\n\\end{{abstract}}")
        else:
            body_parts.append(f"\\section{{{sec.title}}}\n{sec.content}")

    body = "\n\n".join(body_parts)

    return (
        f"{preamble}\n"
        f"\\title{{{title}}}\n"
        f"\\author{{Generated by Research Catalyst}}\n"
        f"\\date{{\\today}}\n\n"
        f"\\begin{{document}}\n"
        f"\\maketitle\n\n"
        f"{body}\n\n"
        f"\\bibliographystyle{{plain}}\n"
        f"\\bibliography{{refs}}\n\n"
        f"\\end{{document}}\n"
    )


def _get_preamble(style: str) -> str:
    template_file = _TEMPLATES_DIR / f"{style}.tex"
    if template_file.is_file():
        return template_file.read_text(encoding="utf-8")

    return (
        "\\documentclass[11pt]{article}\n"
        "\\usepackage[utf8]{inputenc}\n"
        "\\usepackage[T1]{fontenc}\n"
        "\\usepackage{amsmath,amssymb}\n"
        "\\usepackage{graphicx}\n"
        "\\usepackage{hyperref}\n"
        "\\usepackage[margin=1in]{geometry}\n"
        "\\usepackage{natbib}\n"
        "\\usepackage{booktabs}\n"
        "\\usepackage{algorithm}\n"
        "\\usepackage{algorithmic}\n"
    )


# ---------------------------------------------------------------------------
# Word export
# ---------------------------------------------------------------------------

def export_word(
    repo: RepoStructure,
    sections: list[PaperSectionDraft],
    citations: list[CitationEntry],
    job_id: str,
) -> Path:
    """Generate a .docx file with academic formatting.

    Returns path to the generated .docx file.
    """

    try:
        from docx import Document
        from docx.shared import Pt, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise RuntimeError("python-docx is required: pip install python-docx")

    doc = Document()

    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(12)
    paragraph_format = style.paragraph_format
    paragraph_format.space_after = Pt(6)
    paragraph_format.line_spacing = 1.5

    title_text = repo.name.replace("_", " ").title()
    title_para = doc.add_heading(title_text, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    author_para = doc.add_paragraph("Generated by Research Catalyst")
    author_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    author_para.runs[0].font.size = Pt(11)

    doc.add_paragraph()

    for sec in sections:
        if sec.section_id == "abstract":
            doc.add_heading("Abstract", level=1)
            abstract_para = doc.add_paragraph(sec.content)
            abstract_para.runs[0].font.italic = True if abstract_para.runs else None
        else:
            doc.add_heading(sec.title, level=1)
            _add_formatted_content(doc, sec.content)

    if citations:
        doc.add_heading("References", level=1)
        for i, cite in enumerate(citations, 1):
            authors = ", ".join(cite.authors[:5])
            ref_text = f"[{i}] {authors}. {cite.title}. {cite.venue}, {cite.year}."
            if cite.doi:
                ref_text += f" DOI: {cite.doi}"
            doc.add_paragraph(ref_text)

    out_dir = _WORK_DIR / job_id / "word"
    out_dir.mkdir(parents=True, exist_ok=True)
    doc_path = out_dir / f"{repo.name}.docx"
    doc.save(str(doc_path))

    logger.info("Word document exported to %s", doc_path)
    return doc_path


def _add_formatted_content(doc: "Document", content: str) -> None:
    """Add section content, handling basic LaTeX-to-plaintext conversion."""
    import re

    text = content
    text = re.sub(r"\\cite\{([^}]+)\}", r"[\1]", text)
    text = re.sub(r"\\textbf\{([^}]+)\}", r"\1", text)
    text = re.sub(r"\\textit\{([^}]+)\}", r"\1", text)
    text = re.sub(r"\\emph\{([^}]+)\}", r"\1", text)
    text = re.sub(r"\$([^$]+)\$", r"\1", text)

    paragraphs = text.split("\n\n")
    for para_text in paragraphs:
        para_text = para_text.strip()
        if para_text:
            doc.add_paragraph(para_text)


# ---------------------------------------------------------------------------
# Retrieve artifacts
# ---------------------------------------------------------------------------

def get_latex_dir(job_id: str) -> Optional[Path]:
    d = _WORK_DIR / job_id / "latex"
    return d if d.exists() else None


def get_word_path(job_id: str) -> Optional[Path]:
    d = _WORK_DIR / job_id / "word"
    if not d.exists():
        return None
    docs = list(d.glob("*.docx"))
    return docs[0] if docs else None
